name: Laravel Auth Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Laravel Auth Image Build
        run: |
          docker build -t malaknasser26/laravel-auth:latest .

      - name: Laravel Auth Image Push
        run: |
          docker push malaknasser26/laravel-auth:latest
          
   
